//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUser
    {
        public System.Guid AgentUserId { get; set; }
        public Nullable<System.Guid> AgentId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> IsGlobalUser { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
