//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSeria
    {
        public System.Guid AgentSeria1 { get; set; }
        public Nullable<System.Guid> AgentId { get; set; }
        public Nullable<System.Guid> SeriaId { get; set; }
    
        public virtual seria seria { get; set; }
    }
}
