//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.AgentUsers = new HashSet<AgentUser>();
            this.TarifPlanAgents = new HashSet<TarifPlanAgent>();
        }
    
        public System.Guid AgentId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AgentUser> AgentUsers { get; set; }
        public virtual ICollection<TarifPlanAgent> TarifPlanAgents { get; set; }
    }
}
