//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSeria
    {
        public AgentSeria()
        {
            this.Factors = new HashSet<Factor>();
            this.Tarifs = new HashSet<Tarif>();
        }
    
        public System.Guid AgentSeriaId { get; set; }
        public Nullable<System.Guid> AgentId { get; set; }
        public Nullable<System.Guid> SeriaId { get; set; }
        public Nullable<System.Guid> TerritoryGrpId { get; set; }
        public Nullable<decimal> AgentFee { get; set; }
        public bool HidePremium { get; set; }
    
        public virtual TerritoryGrp TerritoryGrp { get; set; }
        public virtual ICollection<Factor> Factors { get; set; }
        public virtual ICollection<Tarif> Tarifs { get; set; }
        public virtual seria seria { get; set; }
    }
}
