//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    
    public partial class agentSalary_Result2
    {
        public System.Guid AgentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> sold { get; set; }
        public Nullable<decimal> Prem { get; set; }
        public Nullable<decimal> PremRur { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> commrur { get; set; }
        public Nullable<int> annul_count { get; set; }
        public Nullable<decimal> annul_sum_rur { get; set; }
        public Nullable<decimal> annul_sum { get; set; }
        public Nullable<decimal> annul_comm { get; set; }
    }
}
