//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public Condition()
        {
            this.ConditionSerias = new HashSet<ConditionSeria>();
            this.ContractConditions = new HashSet<ContractCondition>();
        }
    
        public System.Guid ConditionId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> AddRefsId { get; set; }
    
        public virtual AddRef AddRef { get; set; }
        public virtual ICollection<ConditionSeria> ConditionSerias { get; set; }
        public virtual ICollection<ContractCondition> ContractConditions { get; set; }
    }
}
