//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatu
    {
        public ContractStatu()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public System.Guid ContractStatusId { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Status Status { get; set; }
    }
}
