//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAgent
    {
        public System.Guid ContractAgentId { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.Guid> AgentId { get; set; }
        public Nullable<decimal> Percent { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
