//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurRate
    {
        public System.Guid CurRateId { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public decimal Rate { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
