//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.ContractFactors = new HashSet<ContractFactor>();
        }
    
        public System.Guid IdFactor { get; set; }
        public string FactorType { get; set; }
        public Nullable<decimal> Factor1 { get; set; }
        public Nullable<decimal> ValueFrom { get; set; }
        public Nullable<decimal> ValueTo { get; set; }
        public Nullable<System.Guid> SeriaId { get; set; }
        public Nullable<System.Guid> RiskId { get; set; }
        public string Name { get; set; }
        public bool SingleItemInGroup { get; set; }
        public Nullable<int> Position { get; set; }
        public bool auto { get; set; }
        public Nullable<System.Guid> AgentSeriaId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> RiskProgramId { get; set; }
        public Nullable<int> FactorAccess { get; set; }
    
        public virtual AgentSeria AgentSeria { get; set; }
        public virtual ICollection<ContractFactor> ContractFactors { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
