//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class goDbEntities : DbContext
    {
        public goDbEntities()
            : base("name=goDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<seria> serias { get; set; }
        public virtual DbSet<Contract_territory> Contract_territory { get; set; }
    }
}
