//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_settings
    {
        public System.Guid ImportId { get; set; }
        public Nullable<int> numcol { get; set; }
        public string colcode { get; set; }
        public string colname { get; set; }
    }
}
