//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLogContract
    {
        public System.Guid ImportLogContract1 { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.Guid> ImportLogId { get; set; }
    }
}
