//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskProgram
    {
        public System.Guid RiskProgramId { get; set; }
        public string ProgramCode { get; set; }
        public Nullable<System.Guid> RiskSeriaId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> DefaultInsSum { get; set; }
    }
}
