//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    
    public partial class spMonthPrem_Result1
    {
        public Nullable<int> m { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<decimal> prem { get; set; }
        public string mname { get; set; }
    }
}
