//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public System.Guid SubjectId { get; set; }
        public string Name1 { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Pasport { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
