//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarif
    {
        public System.Guid TarifId { get; set; }
        public System.Guid RiskId { get; set; }
        public Nullable<decimal> InsSumFrom { get; set; }
        public Nullable<decimal> InsSumTo { get; set; }
        public Nullable<double> FranshSum { get; set; }
        public Nullable<double> FranshPerc { get; set; }
        public Nullable<double> PremSum { get; set; }
        public Nullable<System.Guid> SeriaId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<double> InsFee { get; set; }
    
        public virtual Risk Risk { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual seria seria { get; set; }
    }
}
