//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifPlan
    {
        public TarifPlan()
        {
            this.TarifPlanAgents = new HashSet<TarifPlanAgent>();
            this.Tarifs = new HashSet<Tarif>();
        }
    
        public System.Guid TarifPlanId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> SeriaId { get; set; }
    
        public virtual ICollection<TarifPlanAgent> TarifPlanAgents { get; set; }
        public virtual ICollection<Tarif> Tarifs { get; set; }
        public virtual seria seria { get; set; }
    }
}
