//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifPlanAgent
    {
        public System.Guid TarifPlanAgentId { get; set; }
        public System.Guid AgentId { get; set; }
        public System.Guid TarifPlanId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual TarifPlan TarifPlan { get; set; }
    }
}
