//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryGrp
    {
        public TerritoryGrp()
        {
            this.AgentSerias = new HashSet<AgentSeria>();
        }
    
        public System.Guid TerritoryGrpId { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<AgentSeria> AgentSerias { get; set; }
    }
}
