//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_agentseria
    {
        public Nullable<System.Guid> AgentId { get; set; }
        public System.Guid SeriaId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsMulti { get; set; }
        public string formname { get; set; }
        public Nullable<System.Guid> DefaultCurrencyId { get; set; }
        public Nullable<int> AutoNumber { get; set; }
        public string numberformat { get; set; }
        public Nullable<System.Guid> DefaultTerritoryId { get; set; }
        public string PrintFunction { get; set; }
        public Nullable<int> AssuredMax { get; set; }
        public string UserId { get; set; }
    }
}
