//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bordero
    {
        public System.Guid BorderoId { get; set; }
        public Nullable<decimal> DocNum { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<int> Sended { get; set; }
        public Nullable<int> contractcount { get; set; }
    }
}
