//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bordero_new
    {
        public System.Guid BorderoId { get; set; }
        public Nullable<decimal> DocNum { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<int> Sended { get; set; }
        public System.Guid ContractId { get; set; }
        public Nullable<decimal> contractnumber { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public string currcode { get; set; }
        public Nullable<decimal> InsPremRur { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string agentname { get; set; }
    }
}
