//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_contract_factors
    {
        public System.Guid ContractFactorId { get; set; }
        public Nullable<System.Guid> IdFactor { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<decimal> Val_n { get; set; }
        public Nullable<int> Position { get; set; }
        public string Factorname { get; set; }
        public string FactorType { get; set; }
        public Nullable<System.Guid> RiskProgramId { get; set; }
        public int FactorAccess { get; set; }
    }
}
