//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_importlog
    {
        public Nullable<System.DateTime> dateinsert { get; set; }
        public System.Guid ImportLogId { get; set; }
        public string userid { get; set; }
        public string UserName { get; set; }
        public Nullable<int> contractcount { get; set; }
    }
}
