//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Tarifs
    {
        public System.Guid TarifId { get; set; }
        public System.Guid RiskProgramId { get; set; }
        public Nullable<decimal> InsSumFrom { get; set; }
        public Nullable<decimal> InsSumTo { get; set; }
        public Nullable<double> FranshSum { get; set; }
        public Nullable<double> FranshPerc { get; set; }
        public Nullable<double> PremSum { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<double> InsFee { get; set; }
        public Nullable<System.Guid> TarifPlanId { get; set; }
        public Nullable<System.Guid> AgentSeriaId { get; set; }
        public Nullable<int> PeriodFrom { get; set; }
        public Nullable<int> PeriodTo { get; set; }
        public string RepeatedType { get; set; }
        public Nullable<int> RepeatedDays { get; set; }
        public string seria_code { get; set; }
        public string seria_name { get; set; }
        public string risk_code { get; set; }
        public string risk_name { get; set; }
        public string ProgramCode { get; set; }
        public string territory_name { get; set; }
        public System.Guid RiskId { get; set; }
    }
}
